#import "../vol2sty.H.typ": *

#let pages = 1
#let date = "2023-01-02"
#let title = [A Covid Journey]
#let main = [
  I got fever at night on 2022-12-24, and subsequently headache, dizziness, myasthenia, throat pain.
  Although there was no time for a PCR test, I was convinced that the disease must be Covid-19.
  
  The symptoms were not severe. Taking a few tablets of paracetamol per day was sufficient to suppress the body temperature.
  
  I did undergo a scary process of emotional amplification.
  The emotional pulses were particularly strong from time to time.
  Rarely-seen emotions could come out and I was unprepared.
  The experience may be comparable to Pandora or Cthulhu.
  
  One week later, my body almost recovered. Only throat issues remained.
  The whole course of the disease was brief and moderate, much less harmful than the original Covid-19.
  Transmissibility always comes at the cost of pathogenicity.
]
#make_single(date, title, main)
