#import "../vol2sty.H.typ": *

#let pages = 1
#let date = "2026-03-28"
#let title = [Where Are You Toward]
#let main = [
  In societies populated with less ethnic homogeneousness, some people, especially those whose appearances draw speculations on higher correlation to immigration experiences, may encounter interrogations like "where are you from".
  These topic choices may often be labeled "microaggression" in the recent and current political atmosphere especially in societies that host serious racial justice discourses.
  One may be willing to assume friendly attitudes in such questions by default, but when these events stack up, it becomes difficult to neglect the subtle weirdness carried across askers with various demographic statuses.
  While I do not reside in the United States, I can draw relatability from stories shared by other people.

  And I imagined, if I were to be a foreign visitor somewhere having small talks with some nice people,
  I would ask them "where are you toward" before the "where are you from" topic runs into their mind.
  Origin talks can feel like fact-check, but direction talks invite aspirations.
  Someone who understands the weirdness of the recent and current political climate would get the humor from the antonym,
  and someone who understands existentialism would notice the irony --- there is only one destination and it is shared by all human being.

  #quote(
    block: true,
    quotes: false,
    [
      #set text(style: "italic")
      All that lives...\ Will one day die.],
    attribution: [Divine Law (III) #footnote[~2025. miHoYo, Cognosphere (d.b.a. Hoyoverse), et al. Honkai: Star Rail (Version 3.8). Omen in the Trees.]],
  )


  Identification can feel nervous as it anchors one in the society with defined rights and duties (and perhaps also defined fates),
  and all values attached therein are subject to destruction eventually.
  But it is a necessary foundation for socialization,
  the phenomenon responsible to all achievements and disasters in human history,
  so I am ok to live with it.
  If ever one is to be anchored in the perception of another person,
  their aspirations better characterize them than their experiences, and their electing better than their given.
  // If ever characterizing one with social anchors is needed,
  // we can still prefer their destination over their origin,
  // and their electing over their given.




]
#make_single(date, title, main)
